version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocritic
    - misspell
    - unconvert
    - unparam
  settings:
    gosec:
      excludes:
        - G104
  exclusions:
    generated: lax

formatters:
  enable:
    - gofmt
    - goimports
